### ISSUE TITLE
Criar diagrama de classes

### ISSUE THREAD

**Issue by lucasdemoraesc** [DLL-S/superlist#3]

**Comment by lucasdemoraesc** [comment]
@danyelliasmanso e @leonardopereira10 favor revisar o diagrama de classes e os casos de uso.

Atualizei o doc de visão adicionando-os e commitei o arquivo do Astah (pasta superlist-projeto\1. Modelos)

**Comment by leonardopereira10** [comment]
Alterado de "Preco" para "PrecoUnitario"
